version: '3.8'

services:
  zitadel:
    restart: always
    networks:
      - zitadel
    image: ghcr.io/zitadel/zitadel:v2.0.0-v2-alpha.23-amd64
    command: admin --config /.zitadel/config.yaml --steps /.zitadel/steps.yaml start-from-init --masterkey ChangeThis32CharExampleKeyNow!!"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/debug"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./image/:/.zitadel/

  db:
    restart: always
    networks:
      - zitadel
    image: cockroachdb/cockroach:v22.1.0
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 9090:8080
      - 26257:26257

networks:
  zitadel: